name: Retrieve SSH Keys from Google Secret Manager

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  retrieve-ssh-keys:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Retrieve Private Key from Secret Manager
      - name: Retrieve Private Key
        id: private_key
        uses: google-github-actions/secret-manager@v1
        with:
          secret: bastion-ssh-private-key

      # Step 4: Retrieve Public Key from Secret Manager
      - name: Retrieve Public Key
        id: public_key
        uses: google-github-actions/secret-manager@v1
        with:
          secret: bastion-ssh-key-public

      # Step 5: Write SSH Keys to Files
      - name: Write SSH Keys to Files
        run: |
          echo "${{ steps.private_key.outputs.secret }}" > bastion-ssh-private-key.pem
          echo "${{ steps.public_key.outputs.secret }}" > bastion-ssh-key-public.pub
          echo "SSH keys written to files."

      # Step 6: Set File Permissions
      - name: Set File Permissions
        run: |
          chmod 600 bastion-ssh-private-key.pem
          chmod 644 bastion-ssh-key-public.pub
          echo "File permissions set."
          cat bastion-ssh-key-public.pub