name: Retrieve SSH Keys from Google Secret Manager

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  retrieve-ssh-keys:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Install gcloud CLI
      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "latest"

      # Step 4: Retrieve Private Key from Secret Manager
      - name: Retrieve Private Key
        run: |
          gcloud secrets versions access latest --secret="bastion-ssh-private-key" > bastion-ssh-private-key.pem

      # Step 5: Retrieve Public Key from Secret Manager
      - name: Retrieve Public Key
        run: |
          gcloud secrets versions access latest --secret="bastion-ssh-key-public" > bastion-ssh-key-public.pub

      # Step 6: Set File Permissions
      - name: Set File Permissions
        run: |
          chmod 600 bastion-ssh-private-key.pem
          chmod 644 bastion-ssh-key-public.pub
          echo "File permissions set."
          cat bastion-ssh-key-public.pub